map_type: costmap

obstacle_range: 2.0
raytrace_range: 4.0

transform_tolerance: 1.25

robot_radius: 0.4
inflation_radius: 0.75

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
